[workspace]
members = ["bin", "crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["merklefruit", "refcell"]

[profile.dev]
opt-level = 1
overflow-checks = false

[profile.bench]
debug = true
