[package]
name = "op-composer"
description = "A Docker Compose-like tool for managing Op Stack components"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
op-primitives = { path = "../primitives" }

strum.workspace = true
inquire.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_regex.workspace = true
enum-variants-strings.workspace = true

eyre.workspace = true
tracing.workspace = true

hex-literal.workspace = true
once_cell.workspace = true

bollard = "0.15.0"
tokio = { version = "1.11.0", features = ["full"] }

[dev-dependencies]
pretty_assertions = "1"
