[package]
name = "op-up-cli"
version = "0.1.0"
edition = "2021"
authors = ["merklefruit"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
inquire = "0.6.2"
serde = "1.0.163"
serde_json = "1.0.96"
