FROM --platform=$BUILDPLATFORM golang:1.19.0-alpine3.15 as builder

ARG VERSION=v0.0.0

RUN apk add --no-cache make gcc musl-dev linux-headers git jq bash

# build op-challenger with the shared go.mod & go.sum files
COPY ./optimism/op-challenger /app/op-challenger
COPY ./optimism/op-bindings /app/op-bindings
COPY ./optimism/op-node /app/op-node
COPY ./optimism/op-service /app/op-service
COPY ./optimism/op-signer /app/op-signer
COPY ./optimism/go.mod /app/go.mod
COPY ./optimism/go.sum /app/go.sum
COPY ./optimism/.git /app/.git

WORKDIR /app/op-challenger

RUN go mod download

ARG TARGETOS TARGETARCH

RUN make op-challenger VERSION="$VERSION" GOOS=$TARGETOS GOARCH=$TARGETARCH

FROM alpine:3.15

COPY --from=builder /app/op-challenger/bin/op-challenger /usr/local/bin
COPY ./docker/op-challenger-go-entrypoint.sh /op-challenger-go-entrypoint.sh

CMD ["/bin/sh", "/op-challenger-go-entrypoint.sh"]
