name: Manual Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to release. Should match the version in `Cargo.toml`. For example, 0.1.20"
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
    - uses: anothrNick/github-tag-action@master
      env:
        CUSTOM_TAG: v${{ inputs.version }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
