[package]
name = "opup"
description = "Spin up a composable OP Stack, programmatically."

edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
op-config = { path = "../../crates/config" }
op-stack = { path = "../../crates/stack" }

serde.workspace = true
serde_json.workspace = true
eyre.workspace = true
futures.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

bollard = "0.15.0"
project-root = "0.2.2"
tokio = { version = "1.11.0", features = ["full"] }
clap = { version = "4.4.3", features = ["derive"] }

[target.'cfg(not(windows))'.dependencies]
jemallocator = { version = "0.5.0", optional = true }
jemalloc-ctl = { version = "0.5.0", optional = true }

[features]
default = ["jemalloc"]
jemalloc = ["dep:jemallocator", "dep:jemalloc-ctl"]
jemalloc-prof = ["jemalloc", "jemallocator?/profiling"]
