[package]
name = "opup"
description = "Spin up a composable OP Stack, programmatically."

edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
op-composer = { version = "0.1.0", path = "../../crates/composer" }
op-config = { version = "0.1.0", path = "../../crates/config" }
op-primitives = { version = "0.1.0", path = "../../crates/primitives" }
op-contracts = { version = "0.1.0", path = "../../crates/contracts" }
op-stages = { version = "0.1.0", path = "../../crates/stages" }

serde.workspace = true
serde_json.workspace = true
eyre.workspace = true
futures.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

platforms = "3.1"
which = "5.0"
humantime = "2.1"
prettytable-rs = "0.10"
semver = { version = "1.0", features = ["serde"] }
svm-rs = "0.3"
bollard = "0.15"
inquire = "0.6"
tokio = { version = "1.33", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }

[target.'cfg(not(windows))'.dependencies]
jemallocator = { version = "0.5.0", optional = true }
jemalloc-ctl = { version = "0.5.0", optional = true }

[features]
default = ["jemalloc"]
jemalloc = ["dep:jemallocator", "dep:jemalloc-ctl"]
jemalloc-prof = ["jemalloc", "jemallocator?/profiling"]
